// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUkFpLfC4_lJ5Wsz3awnTbFgmR3ZNKdaQ',
    appId: '1:258386620313:web:fd5a1fd98c80ed9b136d08',
    messagingSenderId: '258386620313',
    projectId: 'ditonton-a19f5',
    authDomain: 'ditonton-a19f5.firebaseapp.com',
    storageBucket: 'ditonton-a19f5.appspot.com',
    measurementId: 'G-50DZWFPEXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08Rlz7Ox-l78vnoZcRMYusQMO7yKT85k',
    appId: '1:258386620313:android:40883510611297f2136d08',
    messagingSenderId: '258386620313',
    projectId: 'ditonton-a19f5',
    storageBucket: 'ditonton-a19f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71v87-IlVkZp78aqZOnJDJJiicoVizZ8',
    appId: '1:258386620313:ios:37c66eae56af43ca136d08',
    messagingSenderId: '258386620313',
    projectId: 'ditonton-a19f5',
    storageBucket: 'ditonton-a19f5.appspot.com',
    iosClientId: '258386620313-t7k93ai5l4i3lk6kv8lb30fgi2imv47m.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
